---
- name: Pull kubeadm images
  command: kubeadm config images pull
  register: kubeadm_images

- name: Display kubeadm image pull output
  debug:
    var: kubeadm_images.stdout_lines

- name: Initialize the Kubernetes control plane
  command: >
    kubeadm init
    --pod-network-cidr=192.168.0.0/16
    --apiserver-advertise-address={{ ansible_host }}
  args:
    creates: /etc/kubernetes/admin.conf

- name: Create .kube directory for root user
  file:
    path: /root/.kube
    state: directory
    mode: '0755'

- name: Copy admin.conf to root's kubeconfig
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    mode: '0644'

- name: Create .kube directory for regular user
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    mode: '0755'
  when: ansible_user != 'root'

- name: Copy admin.conf to regular user's kubeconfig
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: yes
    mode: '0644'
  when: ansible_user != 'root'

- name: Change ownership of regular user's kubeconfig
  file:
    path: "/home/{{ ansible_user }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  when: ansible_user != 'root'

- name: Install Calico operator
  command: >
    kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.1/manifests/tigera-operator.yaml

- name: Wait for Calico operator to be ready
  command: >
    kubectl wait --for=condition=available --timeout=600s deployment -n tigera-operator tigera-operator

- name: Install Calico custom resources
  command: >
    kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.1/manifests/custom-resources.yaml